/*

===============================================================================
  DDL Script; Create Bronze Tables
===============================================================================
Script Purpose:
  This script creates Table in the 'bronze' schema, dropping existing tables
  if they already exist.
  Run tgis Script to re-define the DDL structure of 'bronze' Tables
===============================================================================
*/



/* create tables and fields (for crm and erp) */

IF object_id ('bronze.crm_cust_info', 'u') IS NOT NULL
	DROP TABLE bronze.crm_cust_info;
CREATE TABLE bronze.crm_cust_info(
	cst_id INT,
	cst_key NVARCHAR(50),
	cst_firstname NVARCHAR(50),
	cst_lastname NVARCHAR(50),
	cst_material_status NVARCHAR(50),
	cst_gndr NVARCHAR(50),
	cst_create_date DATE
);
IF object_id('bronze.crm_prd_info','u') IS NOT NULL
	DROP TABLE bronze.crm_prd_info;
create table bronze.crm_prd_info(
prd_id INT,
prd_key NVARCHAR(50),
prd_nm NVARCHAR(50),
prd_cost INT,
prd_line NVARCHAR(50),
prd_start_dt DATETIME,
prd_end_dt DATETIME,
);
GO
IF object_id('bronze.crm_sales_details','u') IS NOT NULL
DROP TABLE bronze.crm_sales_details;
create table bronze.crm_sales_details (
sls_ord_num NVARCHAR(50),
sls_prd_key NVARCHAR(50),
sls_cust_id  INT,	
sls_order_dt INT,
sls_ship_dt INT,
sls_due_dt INT,
sls_sales INT,
sls_quantity INT,
sls_price INT
);
GO
IF object_id('bronze.erp_loc_a101','u') IS NOT NULL
DROP TABLE bronze.erp_loc_a101;
create table bronze.erp_loc_a101(
cid NVARCHAR(50),
CNTRY NVARCHAR(50)
);
GO
IF object_id('bronze.erp_cust_az12','u') IS NOT NULL
DROP TABLE bronze.erp_cust_az12;
CREATE TABLE bronze.erp_cust_az12(
cid nvarchar(50),
bdate DATE,
gen NVARCHAR(50)
);
GO

IF object_id ('bronze.erp_px_cat_g1v2', 'u') IS NOT NULL
	DROP TABLE bronze.erp_px_cat_g1v2;

CREATE TABLE bronze.erp_px_cat_g1v2(
id NVARCHAR(50),
cat NVARCHAR(50),
subcat NVARCHAR(50),
maintenance NVARCHAR(50)
);


/*Cretae PROCEDURE */
CREATE OR ALTER PROCEDURE bronze.load_bronze AS
BEGIN
    DECLARE @start_time DATETIME, @end_time DATETIME, @batch_start_time DATETIME, @batch_end_time DATETIME;
    BEGIN TRY
        SET @start_time = GETDATE();
        PRINT '==============================';
        PRINT 'Loading the Bronze Layre';
        PRINT '==============================';
    
        PRINT '------------------------------';
        PRINT 'Loading CRM Tables';
        PRINT '------------------------------';

        SET @start_time = GETDATE();
        PRINT '>> Truncating Table: bronze.crm_cust_info';
        TRUNCATE TABLE bronze.crm_cust_info;

        PRINT '>> Inserting Data Into: bronze.crm_cust_info ';
        BULK insert bronze.crm_cust_info
        FROM 'E:\Data-Engineer\sql-data-warehouse-project\datasets\source_crm\cust_info.csv'
        WITH(
        FIRSTROW = 2,
        FIELDTERMINATOR = ',',
        TABLOCK
        );
        SET @end_time = GETDATE();
        PRINT '>> Load Duration: ' + CAST(DATEDIFF(second, @start_time, @end_time) AS NVARCHAR) + 'second';
        PRINT '----------------------';

        SET @start_time = GETDATE();
        PRINT '>> Truncating Table: bronze.crm_prd_info';
        TRUNCATE TABLE bronze.crm_prd_info;

        PRINT '>> Inserting Data Into: bronze.crm_prd_info ';
        BULK INSERT bronze.crm_prd_info 
        FROM 'E:\Data-Engineer\sql-data-warehouse-project\datasets\source_crm\prd_info.csv'
        WITH
        (
        FIRSTROW = 2,
        FIELDTERMINATOR = ',',
        TABLOCK);
        SET @end_time = GETDATE();
        PRINT '>> Load Duration: ' + CAST(DATEDIFF(second, @start_time, @end_time) AS NVARCHAR) + 'second';
        PRINT '----------------------';

        SET @start_time = GETDATE();
        PRINT '>> Truncating Table: bronze.crm_sales_details';
        TRUNCATE TABLE bronze.crm_sales_details;

        PRINT '>> Inserting Data Into: bronze.crm_sales_details ';
        BULK INSERT bronze.crm_sales_details 
        FROM 'E:\Data-Engineer\sql-data-warehouse-project\datasets\source_crm\sales_details.csv'
        WITH
        (
        FIRSTROW = 2,
        FIELDTERMINATOR = ',',
        TABLOCK);

        SET @end_time = GETDATE();
        PRINT '>> Load Duration: ' + CAST(DATEDIFF(second, @start_time, @end_time) AS NVARCHAR) + 'second';
        PRINT '----------------------';
  
        PRINT '------------------------------';
        PRINT 'Loading ERP Tables';
        PRINT '------------------------------';

        SET @start_time = GETDATE();
        PRINT '>> Truncating Table: bronze.erp_cust_az12';
        TRUNCATE TABLE bronze.erp_cust_az12;

        PRINT '>> Inserting Data Into: bronze.erp_cust_az12 ';
        BULK INSERT bronze.erp_cust_az12
        FROM 'E:\Data-Engineer\sql-data-warehouse-project\datasets\source_erp\CUST_AZ12.csv'
        WITH(
        FIRSTROW = 2,
        FIELDTERMINATOR = ',',
        TABLOCK
        );
        SET @end_time = GETDATE();
        PRINT '>> Load Duration: ' + CAST(DATEDIFF(second, @start_time, @end_time) AS NVARCHAR) + 'second';
        PRINT '----------------------';
  
        SET @start_time = GETDATE();
        PRINT '>> Truncating Table: bronze.erp_loc_a101';
        TRUNCATE TABLE bronze.erp_loc_a101;

        PRINT '>> Inserting Data Into: bronze.erp_loc_a101 ';
        BULK INSERT bronze.erp_loc_a101
        FROM 'E:\Data-Engineer\sql-data-warehouse-project\datasets\source_erp\LOC_A101.csv'
        WITH(
        FIRSTROW = 2,
        FIELDTERMINATOR = ',',
        TABLOCK
        );
        SET @end_time = GETDATE();
        PRINT '>> Load Duration: ' + CAST(DATEDIFF(second, @start_time, @end_time) AS NVARCHAR) + 'second';
        PRINT '----------------------';
  
        SET @start_time = GETDATE();
        PRINT '>> Truncating Table: bronze.erp_px_cat_g1v2';
        TRUNCATE TABLE bronze.erp_px_cat_g1v2;

        PRINT '>> Inserting Data Into: bronze.erp_px_cat_g1v2 ';
        BULK INSERT bronze.erp_px_cat_g1v2
        FROM 'E:\Data-Engineer\sql-data-warehouse-project\datasets\source_erp\PX_CAT_G1V2.csv'
        WITH(
        FIRSTROW = 2,
        FIELDTERMINATOR = ',',
        TABLOCK
        );
        SET @end_time = GETDATE();
        PRINT '>> Load Duration: ' + CAST(DATEDIFF(second, @start_time, @end_time) AS NVARCHAR) + 'second';
        PRINT '----------------------';

        
        SET @batch_end_time = GETDATE();
        PRINT '===============================';
        PRINT 'Loading Bronze Layer is Completed';
        PRINT '>> - Total Bronze Loading Duration: ' + CAST(DATEDIFF(second, @batch_start_time, @batch_end_time) AS NVARCHAR) + 'second';
        PRINT '===============================';

      END TRY
      BEGIN CATCH
        PRINT '====================================='
        PRINT 'Error Message' + ERROR_MESSAGE();
        PRINT 'Error Message' + CAST(ERROR_NUMBER() AS NVARCHAR);
        PRINT 'Error Message' + CAST(ERROR_STATE() AS NVARCHAR);
        PRINT '====================================='
      END CATCH
END
